<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<h1>Bem-Vindo <?php echo $this->db->get_where('user', array('id' => $user_id))->row()->first_name ?></h1>
<br>
<button onclick="window.location='<?php echo site_url('/user/user/') ?>'">Voltar</button>
<p>Esta é a página para adicionar turma</p>
<br>
<?php echo form_open('user/user/searchTurma') ?>
    <input type="text" class="form-control" placeholder="Nome da Turma" name="classroomname">
<br>
<?php echo form_submit('', 'Buscar', "class='btn btn-primary  btn-block'");
echo form_close(); ?>

<?php 
echo $table;
?>