<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<h1>Bem-Vindo <?php echo $this->db->get_where('user', array('id' => $user_id))->row()->first_name ?></h1>
<br>
<button onclick="window.location='<?php echo site_url('/user/user/logout') ?>'">Logout</button>
<p>Esta é a página do usuário</p>
<?php

 echo var_dump($table);
?>
<br>
<button type="button" class="btn btn-success"
onclick="window.location='<?php echo site_url('/user/user/addTurma') ?>' "  >Adicionar Turma</button>
