<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light"
		th:fragment="dashboard-navbar(brand, role, activePage)">
		<div class="container">
      <a class="navbar-brand" href="#">Where is my classroom</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

  			<div class="collapse navbar-collapse" id="navbarNav">
  				<ul class="navbar-nav mr-auto">
  					<li>
  						<a href="#" class="nav-link">Minhas Turmas</a>
  					</li>
  				</ul>

  				<ul class="navbar-nav ml-auto">
  					<!--<li class="nav-item"><span class="navbar-text">Vynicius</span></li>-->
  					<li class="nav-item pl-3">
  						<form method="post">
  							<input type="submit" class="form-control link-button"
  								value="Login" />
  						</form>
  					</li>
  				</ul>
  			</div>
  		</div>
  </nav>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <div class="form-row justify-content-center">
        <div class="col-md-11">
          <input class="form-control" name="search">
        </div>
        <div class="col-md-1">
          <button class="btn btn-primary">Procurar</button>
        </div>
    </div>
    </div>
  </div>

  <div class="row mt-4 justify-content-center">
    <div class="col-md-12">
      <div class="card-deck">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Engenharia De Software I</h3>
            <h6 class="card-subtitle mb-4 text-muted">Leonardo Murta</h6>
            <p class="card-text">18:00 - 20:00</p>
            <p class="card-text">Segunda, Quarta</p>
            <p class="card-text">Campus da Praia Vermelha - Prédio do IC</p>
            <p class="card-text">Sala 404</p>
            <a href="#" class="card-link">Google Maps</a>

            <div class="custom-control custom-checkbox float-right">
              <input type="checkbox" class="custom-control-input" id="customCheck1">
              <label class="custom-control-label" for="customCheck1">Inscrito</label>
            </div>

          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Engenharia De Software I</h3>
            <h6 class="card-subtitle mb-4 text-muted">Leonardo Murta</h6>
            <p class="card-text">18:00 - 20:00</p>
            <p class="card-text">Segunda, Quarta</p>
            <p class="card-text">Campus da Praia Vermelha - Prédio do IC</p>
            <p class="card-text">Sala 404</p>
            <a href="#" class="card-link">Google Maps</a>

            <div class="custom-control custom-checkbox float-right">
              <input type="checkbox" class="custom-control-input" id="customCheck2">
              <label class="custom-control-label" for="customCheck2">Inscrito</label>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

</body>
</html>
