<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">

    <link rel="stylesheet" href="<?php echo base_url('assets/css/home.css') ?>">

    <style>

    </style>

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light"
		th:fragment="dashboard-navbar(brand, role, activePage)">
		<div class="container">
      <a class="navbar-brand" href="<?php echo base_url() ?>">Where is my classroom</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  			<div class="collapse navbar-collapse" id="navbarNav">
  				<ul class="navbar-nav mr-auto">
          <?php

          if ($this->session->userdata('is_admin') != null) {
            if ($this->session->userdata('is_admin')) {
              $title = 'Turmas';
              $link = site_url('admin/Admin');
              $logout = site_url('/admin/admin/logout');
            } else{
              $title = 'Minhas Turmas';
              $link = site_url('user/User');
              $logout = site_url('/user/user/logout');
            }

          ?>
  					<li>
  						<a href="<?php echo $link ?>" class="nav-link"><?php echo $title ?></a>
  					</li>
          <?php }?>
  				</ul>

  				<ul class="navbar-nav ml-auto">
            <!--<li class="nav-item"><span class="navbar-text">Vynicius</span></li>-->
            <?php if (!$this->session->userdata('logged')) : ?>
                <li class="nav-item pl-3">
                <?php echo form_open('home/login'); ?>
                <?php echo form_submit('', 'Login', "class='form-control link-button'"); ?>
                <?php echo form_close(); ?>
                </li>
            <?php else : ?>
                <li class="nav-item"><span class="navbar-text"><?php echo $this->session->userdata('user_firstname') ?></span></li>
                <li class="nav-item pl-3">
                <button class='form-control link-button' onclick="window.location='<?php echo $logout ?>'">Logout</button>
            <?php endif; ?>
  				</ul>
  			</div>
  		</div>
  </nav>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <div class="form-row justify-content-center">
        <div class="col-md-11">
          <?php echo form_open('Home/searchTurma'); ?>
            <input class="form-control" name="search">
        </div>
        <div class="col-md-1">
          <?php echo form_submit('', 'Procurar', "class='btn btn-primary'"); ?>
          <?php echo form_close(); ?>
          <!-- <button class="btn btn-primary">Procurar</button> -->
        </div>
    </div>
    </div>
  </div>
  <div class="row mt-4 justify-content-center">

    <div class="col-md-12">
      <div class="card-columns">
        <?php if (!empty($table)) : ?>
        <?php foreach ($table as $key => $row) : ?>
          <div class="card">
            <div class="card-body">
              <h3 class="card-title"><?php echo $row["turma"] ?></h3>
              <h6 class="card-subtitle mb-4 text-muted"><?php echo $row["professor"] ?></h6>
              <p class="card-text"><?php echo $row["horario_ini"] . ' - ' . $row["horario_fim"] ?></p>
              <p class="card-text"><?php echo $row["dia"] ?></p>
              <p class="card-text"><?php echo $row["campus"] . ' - ' . $row["predio"] ?></p>
              <p class="card-text"><?php echo $row["sala"] ?></p>
              <a href="#" class="card-link">Google Maps</a>
              <div class="custom-control custom-checkbox float-right">
                <!-- Cada $row da $table_row precisa ter alguma propriedade checked=true/false que deve ser inserida
                  no controller antes de vir pra ca -->
                <input type="checkbox" class="custom-control-input subscriptionCheckbox" id="customCheck<?php echo $key ?>">
                <label class="custom-control-label" for="customCheck<?php echo $key ?>">Inscrito</label>
              </div>
              <!--<?php if ($this->session->userdata('is_admin') == 0) : ?>
                <?php if (!empty($table_user)) : ?>
                  <?php foreach ($table_user as $tu) : ?>
                      <?php if ($tu["id"] == $row["id"]) : ?>
                        <script> checkbox.checked = true;</script>
                      <?php endif; ?>
                  <?php endforeach; ?>
                <?php endif; ?>
              <?php endif;?>-->
            </div>
          </div>

      <?php endforeach; ?>
      <?php endif; ?>          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

<script>
  $(".subscriptionCheckbox").change(function() {
      if(this.checked) {
          console.log(this.id + ' -> checked');
      }else{
        console.log(this.id + ' -> not checked');
      }
  });
</script>

</body>
</html>
