<?php
//defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Login</title>
	<link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">
	<link rel="stylesheet" href="<?php echo base_url('assets/css/home.css') ?>">
</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light" th:fragment="dashboard-navbar(brand, role, activePage)">
		<div class="container">
			<a class="navbar-brand" href="<?php echo base_url() ?>">Where is my classroom</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a href="<?php echo site_url('admin/admin') ?>" class="nav-link">Turmas</a>
					</li>
					<li class="nav-item">
						<a href="<?php echo site_url('admin/admin/subjects') ?>" class="nav-link">Matérias</a>
					</li>
					<li class="nav-item">
						<a href="<?php echo site_url('admin/admin/teachers') ?>" class="nav-link">Professores</a>
					</li>
					<li class="nav-item">
						<a href="<?php echo site_url('admin/admin/periods') ?>" class="nav-link">Períodos</a>
					</li>
				</ul>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item"><span class="navbar-text">
							<?php echo $this->db->get_where('user', array('id' => $user_id))->row()->first_name ?></span></li>
					<li class="nav-item pl-3">
						<button class='form-control link-button' onclick="window.location='<?php echo site_url('/admin/admin/logout') ?>'">Logout</button>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container mt-4">

		<div class="row justify-content-center">
			<div class="col-md-12">
				<div class="registration-form card">
					<div class="card-body">
						<h3 class="card-title">
						<?php if (!strcmp($action, 'editar')) : ?>
						Editar Turma
						<?php else : ?>
						Criar Turma
						<?php endif; ?>
						</h3>
						<div class="card-text">

							<form autocomplete="off" action="#" th:action="@{/registration-company}" th:object="${company}" method="post" class="form" role="form">

								<div class="form-row">
									<div class="form-group col-md-4">
										<label for="teacher-select">Professor</label>
										<select class="custom-select" id="teacher-select">
											<option selected value="1">One</option>
											<option value="2">Two</option>
											<option value="3">Three</option>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="subject-select">Matéria</label>
										<select class="custom-select" id="subject-select">
											<option selected value="1">One</option>
											<option value="2">Two</option>
											<option value="3">Three</option>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="period-select">Período</label>
										<select class="custom-select" id="period-select">
											<option selected value="1">One</option>
											<option value="2">Two</option>
											<option value="3">Three</option>
										</select>
									</div>
								</div>
								<hr />
								<div class="form-row">
									<div class="form-group col-md-4">
										<label for="name-input">Campus</label>
										<input type="text" placeholder="Praia Vermelha" class="form-control" id="campus-input" required />
									</div>
									<div class="form-group col-md-4">
										<label for="name-input">Prédio</label>
										<input type="text" placeholder="Instituto De Computação" class="form-control" id="building-input" required />
									</div>
									<div class="form-group col-md-4">
										<label for="name-input">Endereço</label>
										<input type="text" placeholder="Rua Das Coves" class="form-control" id="address-input" required />
									</div>
								</div>
								<div class="form-row">
									<div class="form-group col-md-4">
										<label for="name-input">Número</label>
										<input type="text" placeholder="1000" class="form-control" id="number-input" required />
									</div>
									<div class="form-group col-md-4">
										<label for="period-select">Tipo de Sala</label>
										<select class="custom-select" id="room-type-select">
											<option selected value="1">Sala</option>
											<option value="2">Laboratório</option>
										</select>
									</div>
								</div>
								<hr />
								<div class="form-row">
									<div class="col-md-6 form-group mt-4">
										<div class="form-check form-check-inline ">
											<input class="form-check-input" type="checkbox" name="weekDayOptions" id="firstWeekDay1" value="1">
											<label class="form-check-label" for="firstWeekDay1">Segunda</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions" id="firstWeekDay2" value="2">
											<label class="form-check-label" for="firstWeekDay2">Terça</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions" id="firstWeekDay3" value="3">
											<label class="form-check-label" for="firstWeekDay3">Quarta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions" id="firstWeekDay4" value="4">
											<label class="form-check-label" for="firstWeekDay4">Quinta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions" id="firstWeekDay5" value="5">
											<label class="form-check-label" for="firstWeekDay5">Sexta</label>
										</div>
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" name="weekDayOptions" id="firstWeekDay6" value="6">
											<label class="form-check-label" for="firstWeekDay6">Sábado</label>
										</div>
									</div>
									<div class="form-group col-md-2">
										<label for="name-input">Horário de Início</label>
										<input type="time" placeholder="18:00" class="form-control" id="start-time-input" required />
									</div>
									<div class="form-group col-md-2">
										<label for="name-input">Horário de Término</label>
										<input type="time" placeholder="20:00" class="form-control" id="end-time-input" required />
									</div>
								</div>
								<hr />
								<div class="form-row">
									<div class="form-group col-md-12">
										<button type="submit" class="btn btn-primary btn-block">Salvar</button>
									</div>
								</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
	<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
	<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

</body>

</html>
