<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?php echo base_url('assets/css/home.css') ?>">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light"
		th:fragment="dashboard-navbar(brand, role, activePage)">
		<div class="container">
      <a class="navbar-brand" href="<?php echo base_url() ?>">Where is my classroom</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  			<div class="collapse navbar-collapse" id="navbarNav">

  				<ul class="navbar-nav ml-auto">
  					<li class="nav-item"><span class="navbar-text"><?php echo $this->db->get_where('user', array('id' => $user_id))->row()->first_name ?></span></li>
  					<li class="nav-item pl-3">
            <button class='form-control link-button' onclick="window.location='<?php echo site_url('/admin/admin/logout') ?>'">Logout</button>
  					</li>
  				</ul>
  			</div>
  		</div>
  </nav>

  <div class="row mt-4 justify-content-center">

    <div class="col-md-12">
      <div class="card-columns">
        <?php if(!empty($table)): ?>
        <?php foreach($table as $row) : ?>
          <div class="card">
            <div class="card-body">
              <h3 class="card-title"><?php echo $row["turma"] ?></h3>
              <h6 class="card-subtitle mb-4 text-muted"><?php echo $row["professor"] ?></h6>
              <p class="card-text"><?php echo $row["horario_ini"] . ' - ' . $row["horario_fim"] ?></p>
              <p class="card-text"><?php echo $row["dia"] ?></p>
              <p class="card-text"><?php echo $row["campus"] . ' - ' . $row["predio"] ?></p>
              <p class="card-text"><?php echo $row["sala"] ?></p>
              <p class="card-text" style="text-align: right;">Editar</p>
              <p class="card-text" style="text-align: right;">Excluir</p>
              <a href="#" class="card-link">Google Maps</a>
            </div>
          </div>

      <?php endforeach; ?>
      <?php //$table[] = '' ?>
      <?php endif; ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

</body>
</html>
