<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Login</title>
	<link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">
	<link rel="stylesheet" href="<?php echo base_url('assets/css/home.css') ?>">
</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light" th:fragment="dashboard-navbar(brand, role, activePage)">
		<div class="container">
			<a class="navbar-brand" href="<?php echo base_url() ?>">Where is my classroom</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a href="<?php echo site_url('admin/admin') ?>" class="nav-link">Turmas</a>
					</li>
					<li class="nav-item">
						<a href="<?php echo site_url('admin/admin/subjects') ?>" class="nav-link">Matérias</a>
					</li>
					<li class="nav-item active">
						<a href="<?php echo site_url('admin/admin/teachers') ?>" class="nav-link">Professores</a>
					</li>
					<li class="nav-item">
						<a href="<?php echo site_url('admin/admin/periods') ?>" class="nav-link">Períodos</a>
					</li>
				</ul>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item"><span class="navbar-text">
							<?php echo $this->db->get_where('user', array('id' => $user_id))->row()->first_name ?></span></li>
					<li class="nav-item pl-3">
						<button class='form-control link-button' onclick="window.location='<?php echo site_url('/admin/admin/logout') ?>'">Logout</button>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container mt-4">
		<div class="row">
			<div class="col-md-12">
				<div class="form-row justify-content-center">
					<div class="col-md-10">
						<!--TODO:fazer isso funcionar-->
						<?php echo form_open('admin/admin/searchTeachers'); ?>
						<input class="form-control" name="search">
					</div>
					<div class="col-md-1">
						<?php echo form_submit('', 'Procurar', "class='btn btn-primary'"); ?>
						<?php echo form_close(); ?>
						<!-- <button class="btn btn-primary">Procurar</button> -->
					</div>
					<div class="col-md-1">
						<button type="button" data-js="create-button" class="btn btn-success">Criar</button>
					</div>
				</div>
			</div>
		</div>
		<div class="row mt-4 justify-content-center">

			<div class="col-md-12">
				<div class="list-group">
				<?php if (!empty($table)): ?>
					<?php foreach ($table as $row): ?>
					<a href="#" class="list-group-item list-group-item-action flex-column align-items-start" data-toggle="modal" data-target="#exampleModalCenter">
						<div class="d-inline-flex justify-content-between">
							<h5 class="mb-1" data-js="teacher-name"><?php echo $row->name ?></h5>
						</div>
						<img src="<?php echo site_url() . $row->img_url ?>" data-js="teacher-image" style="max-width:90px; height:auto" class="rounded float-right">
						<!-- <img src="<?php echo site_url() . 'teacherimage/Leonardo_Murtaball.png' ?>" data-js="teacher-image" style="max-width:90px; height:auto" class="rounded float-right"> -->
						<p class="mb-1">Professor Adjunto</p>
						<p data-js="id" hidden><?php echo $row->id ?></p>
					</a>
					<?php endforeach;?>
				<?php endif;?>

				</div>
			</div>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="modal-title">Criar Novo Professor</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<?php echo form_open_multipart('admin/admin/modalTeacher', 'id="form-modal"') ?>
						<input name="action" id="action" hidden/>
						<div class="form-group">
							<label for="name">Nome</label>
							<input class="form-control" type="text" name="name" placeholder="Nome" required>
						</div>
						<div class="form-group">
              			<label for="teacherImage">Foto</label>
							<div class="input-group mb-3">
								<div class="custom-file">
									<input type="file" class="custom-file-input" id="teacherImage" name="teacherImage" aria-describedby="inputGroupFileAddon01">
									<label class="custom-file-label" id="teacherImageLabel" for="teacherImage">Selecione um arquivo</label>
								</div>
							</div>
						</div>
						<input name="id" hidden>
						<div class="modal-footer">
							<?php echo form_submit('', 'Deletar', 'data-js="delete-button", class="btn btn-danger mr-auto", id="bDelete"') ?>
							<?php echo form_submit('', 'Salvar', 'class="btn btn-primary", id="bSave"') ?>
						</div>
					<?php echo form_close() ?>
				</div>
			</div>
		</div>
  </div>

		<script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
		<script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
		<script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>

    <script>
      (function($) {
        var modal = $('.modal').first();

        var deleteButton = modal.find('[data-js="delete-button"]').first();

        var modalImgInput = modal.find("#teacherImage").first();
        var modalImgLabel = modal.find("#teacherImageLabel").first();

        var modalTitle = modal.find('#modal-title').first();
		var modalIdInput = modal.find('.modal-body input[name="id"]').first();
        var modalNameInput = modal.find('.modal-body input[name="name"]').first();

        function resetInput(){
          modalTitle.text('Criar Novo Professor');
          modal.find('form')[0].reset();
        }

        //add button clicked
        $('[data-js="create-button"').click(function(){
			resetInput();
			deleteButton.hide();
			modal.modal('show');
			var action = document.getElementById('action');
			action.value = 'create';
        });

        modalImgInput.change(function() {
          modalImgLabel.text(modalImgInput.first().val());
        });

        //list item clicked
        $('.list-group-item').click(function() {
        	deleteButton.show();
        	var elem = $( this );
			var id = elem.find('[data-js="id"]').text();
        	var teacherName = elem.find('[data-js="teacher-name"]').text()
			var action = document.getElementById('action');
			var bSave = document.getElementById('bSave');
			var bDelete = document.getElementById('bDelete');
			bSave.addEventListener('click', function(){
				action.value = 'edit'
			});
			bDelete.addEventListener('click', function(){
				action.value = 'delete'
			});
			modalTitle.text(teacherName);
        	modalNameInput.val(teacherName);
			modalIdInput.val(id);
        });

      })(jQuery);
    </script>

</body>

</html>
